indent_style = "Block"
unstable_features = true
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
brace_style = "PreferSameLine"
where_single_line = true
force_multiline_blocks = true
normalize_comments = true
reorder_imported_names = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
struct_field_align_threshold = 4
wrap_comments = true